version: "3.8"

services:
  robertovicario_com-webapp:
    image: robertovicario_com-webapp:3.0.0
    container_name: robertovicario_com-webapp
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
